from dataclasses import dataclass, asdict
from datetime import datetime

@dataclass
class Note:
    id: int = None  # Autogenerated by the database
    title: str = ""
    content: str = ""
    category: str = ""
    tags: str = ""  # Comma-separated tags
    created_at: str = None
    updated_at: str = None

    def to_dict(self):
        return asdict(self)

    @staticmethod
    def from_dict(data: dict):
        return Note(
            id=data.get('id'),
            title=data.get('title', ''),
            content=data.get('content', ''),
            category=data.get('category', ''),
            tags=data.get('tags', ''),
            created_at=data.get('created_at'),
            updated_at=data.get('updated_at')
        )

    @staticmethod
    def current_timestamp():
        return datetime.now().strftime('%Y-%m-%d %H:%M:%S')
